---
# lovelace_gen
title: Environment
icon: mdi:cloud-outline
path: environment
cards:
  - type: vertical-stack
    title: BOM Current Conditions
    cards:
      - type: entities
        # title: BOM Conditions
        entities:
          - entity: sensor.outdoor_thermal_comfort_thermal_perception
            name: Thermal Comfort
            secondary_info: last-updated
          - entity: sensor.bom_home_temp_feels_like
            name: Feels like
            secondary_info: last-updated
          # - entity: sensor.bom_home_temp
          #   name: Temperature
          #   secondary_info: last-updated
          # - entity: sensor.bom_home_humidity
          #   name: Humidity
          #   secondary_info: last-updated
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.bom_home_temp
                name: Temperature
            line_width: 2
            font_size: 70
            hours_to_show: 24
            points_per_hour: 4
            show:
              extrema: true
              fill: true
            color_thresholds:
              - value: 20
                color: "#f39c12"
              - value: 21
                color: "#d35400"
              - value: 21.5
                color: "#c0392b"
            title: Temperature
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.bom_home_humidity
                name: Humidity
            line_width: 2
            font_size: 70
            hours_to_show: 24
            points_per_hour: 4
            show:
              extrema: true
              fill: true
            title: Humidity
              # - entity: sensor.enviroplus_1_humidity
              #   name: Enviro+
      - type: entities
        # title: BOM Conditions
        entities:
          - entity: sensor.bom_home_rain_since_9am
            name: Rain since 9am
            icon: mdi:weather-rainy
            secondary_info: last-updated
          - entity: sensor.outdoor_thermal_comfort_dew_point
            name: Dew Point
            secondary_info: last-updated
          - entity: sensor.outdoor_thermal_comfort_frost_point
            name: Frost Point
            secondary_info: last-updated
          - entity: sensor.outdoor_thermal_comfort_frost_risk
            name: Frost Risk
            secondary_info: last-updated

  - type: "custom:sun-card"
    name: Sun
    meridiem: false
    entities:
      max_elevation: sun.sun
      sunrise: sensor.sunrise
      sunset: sensor.sunset
      noon: sensor.solar_noon
      moon_phase: sensor.moon_phase

  - type: vertical-stack
    title: BOM Forecast
    cards:
      - type: custom:bom-weather-card
        # title: BOM Weather
        entity_current_conditions: sensor.bom_home_icon_descriptor_0
        entity_temperature: sensor.bom_home_temp
        entity_forecast_high_temp_1: sensor.bom_home_temp_max_1
        entity_forecast_high_temp_2: sensor.bom_home_temp_max_2
        entity_forecast_high_temp_3: sensor.bom_home_temp_max_3
        entity_forecast_high_temp_4: sensor.bom_home_temp_max_4
        entity_forecast_high_temp_5: sensor.bom_home_temp_max_5
        entity_forecast_icon_1: sensor.bom_home_icon_descriptor_1
        entity_forecast_icon_2: sensor.bom_home_icon_descriptor_2
        entity_forecast_icon_3: sensor.bom_home_icon_descriptor_3
        entity_forecast_icon_4: sensor.bom_home_icon_descriptor_4
        entity_forecast_icon_5: sensor.bom_home_icon_descriptor_5
        entity_forecast_low_temp_1: sensor.bom_home_temp_min_1
        entity_forecast_low_temp_2: sensor.bom_home_temp_min_2
        entity_forecast_low_temp_3: sensor.bom_home_temp_min_3
        entity_forecast_low_temp_4: sensor.bom_home_temp_min_4
        entity_forecast_low_temp_5: sensor.bom_home_temp_min_5
        entity_summary_1: sensor.bom_home_short_text_1
        entity_summary_2: sensor.bom_home_short_text_2
        entity_summary_3: sensor.bom_home_short_text_3
        entity_summary_4: sensor.bom_home_short_text_4
        entity_summary_5: sensor.bom_home_short_text_5
        entity_sun: sun.sun
        # # entity_visibility: If provided from a different source
        # entity_daytime_high: sensor.bom_today_max
        # entity_daytime_low: sensor.bom_today_min
        entity_wind_bearing: sensor.bom_home_wind_direction
        entity_wind_speed: sensor.bom_home_wind_speed_kilometre
        entity_wind_gust: sensor.bom_home_gust_speed_kilometre
        # # entity_wind_speed_kt: sensor.bom_home_wind_speed_knot
        # # entity_wind_gust_kt: sensor.bom_home_gust_speed_knot
        entity_humidity: sensor.bom_home_humidity
        # # entity_pressure: sensor.nodemcu_lounge_bme280_seapressure I get pressure from a NodeMCU. Bom does not supply this!
        entity_apparent_temp: sensor.bom_home_temp_feels_like
        entity_daily_summary: sensor.bom_home_extended_text_0
        entity_pop: sensor.bom_home_rain_chance_0
        entity_pop_intensity: sensor.bom_home_rain_since_9am
        entity_possible_today: sensor.bom_home_rain_amount_range_0
        entity_pos_1: sensor.bom_home_rain_amount_range_1
        entity_pos_2: sensor.bom_home_rain_amount_range_2
        entity_pos_3: sensor.bom_home_rain_amount_range_3
        entity_pos_4: sensor.bom_home_rain_amount_range_4
        entity_pos_5: sensor.bom_home_rain_amount_range_5
        entity_pop_1: sensor.bom_home_rain_chance_1
        entity_pop_2: sensor.bom_home_rain_chance_2
        entity_pop_3: sensor.bom_home_rain_chance_3
        entity_pop_4: sensor.bom_home_rain_chance_4
        entity_pop_5: sensor.bom_home_rain_chance_5
        # entity_current_text: sensor.bom_current_text # does not work
        # entity_uv_alert: sensor.bom_uv_alert
        # entity_fire_danger: sensor.bom_fire_danger
        entity_uv_alert_summary: sensor.bom_home_uv_category_0
        entity_fire_danger_summary: sensor.bom_home_fire_danger_0
        locale: en
        sunset: true
        static_icons: false
        old_icon: hybrid
        tooltip_bg_color: "rgb( 75,155,239)"
        tooltip_border_color: "rgb(255,161,0)"
        tooltip_border_width: 1
        tooltip_caret_size: 5
        tooltip_fg_color: "#fff"
        tooltip_left_offset: -12
        tooltip_width: 110
        tooltips: true
        old_daily_format: false
        time_format: 12
        show_beaufort: false
        # #           show_decimals: true
        # refresh_interval: 60
        # #           tempformat: highlow OPTIONAL to show max/min in daily
        # show_separator: false
        temp_top_margin: 0px #default 0px px or em Note: pre-0.109.x default was -0.3em
        temp_font_weight: 300 #default 300 numeric
        temp_font_size: 4em #default 4em em
        temp_right_pos: 0.85em #default .85em px or em
        temp_uom_top_margin: -12px #default -12px px or em Note: pre-0.109.x default was -9px
        temp_uom_right_margin: 4px #default 4px px or em
        apparent_top_margin: 45px #default 45px px or em
        apparent_right_pos: 1em #default 1em px or em
        apparent_right_margin: 1em #default 1em px or em
        current_text_top_margin: 4.5em #default 4.5em px or em pre-0.109.x default was 39px
        current_text_left_pos: 0px #default 0px px or em pre-0.109.x default was 5em
        current_text_font_size: 1.5em #default 1.5em em
        current_text_alignment: center #default center
        current_text_width: 100% #default 100%
        current_data_top_margin: 10em #default 10em px or em pre-0.109.x default was 7em
        large_icon_top_margin: -3.2em #default -3.2em px or em Note: pre-0.109.x default was -3.5em
        large_icon_left_position: 0px #default 0em px or em
        separator_top_margin: 6em #default 6em px or em
        summary_top_padding: 2em #default 2em px or em pre-0.109.x default was 1em
        summary_font_size: 0.8em #default 0.8em px or em
        slot_l1: daytime_high #daytime_high
        slot_l2: daytime_low #daytime_low
        slot_l3: wind #wind
        # ######### change slot_l4 to something else if you don't have a pressure entity (otherwise it will be blank on the card
        # slot_l4: pressure #pressure
        # slot_l5: sun_next #sun_next
        # slot_r1: pop #pop
        # slot_r2: humidity #humidity
        # slot_r3: uv_summary #uv_summary
        # slot_r4: fire_summary #fire_summary
        # slot_r5: sun_following #sun_following

  - type: entities
    title: Rainfall
    entities:
      - entity: sensor.rainfall_daily
        name: Daily
        secondary_info: last-updated
      - entity: sensor.rainfall_monthly
        name: Month
        secondary_info: last-updated
      - entity: sensor.rainfall_annual
        name: Year
        secondary_info: last-updated

  - type: statistics-graph
    title: Temperature
    entities:
      - sensor.outdoor_temperature
      - sensor.indoor_temperature

 



  - type: vertical-stack
    cards:
      - type: "custom:bom-radar-card"
        frame_count: 10
        center_latitude: !secret home_latitude
        center_longitude: !secret home_longitude
        marker_latitude: !secret home_latitude
        marker_longitude: !secret home_longitude
        show_marker: true
        show_range: true
        show_radar_location: true
        show_radar_coverage: true
        # show_zoom: true
        # show_recenter: true
        show_playback: true
        static_map: true
        zoom_level: 8

      - type: "custom:bom-radar-card"
        frame_count: 144
        frame_delay: 100
        marker_latitude: !secret home_latitude
        marker_longitude: !secret home_longitude
        show_marker: true
        show_range: false
        static_map: true

  # - type: entities
  #   title: Pollen
  #   icon: mdi:flower
  #   show_header_toggle: true
  #   state_color: true
  #   entities:
  #     - sensor.pollen_grass
  #     - sensor.pollen_grass_risk
  #     - sensor.pollen_tree
  #     - sensor.pollen_tree_risk
  #     - sensor.pollen_weed
  #     - sensor.pollen_weed_risk

  # - type: entities
  #   title: Air Quality (Ambee)
  #   icon: mdi:factory
  #   show_header_toggle: true
  #   state_color: true
  #   entities:
  #     - sensor.air_quality_air_quality_index
  #     - sensor.air_quality_carbon_monoxide
  #     - sensor.air_quality_nitrogen_dioxide
  #     - sensor.air_quality_ozone
  #     - sensor.air_quality_particulate_matter_10
  #     - sensor.air_quality_particulate_matter_2_5
  #     - sensor.air_quality_sulphur_dioxide

  - type: vertical-stack
    title: UV Level
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            # title: UV Level
            icon: mdi:weather-sunny
            entities:
              - entity: sensor.current_ozone_level
                name: Current Ozone Level
                secondary_info: last-updated
              - entity: sensor.current_uv_level
                name: Current UV Level
                secondary_info: last-updated
              - entity: sensor.current_uv_index
                name: Current UV Index
                secondary_info: last-updated
              - entity: sensor.max_uv_index
                name: Maximum UV Index
                secondary_info: last-updated
          - type: history-graph
            hours_to_show: 12
            entities:
              - entity: sensor.current_uv_level
                name: UV Level

  # - type: vertical-stack
  #   cards:
  #     - type: entities
  #       title: Air Quality
  #       entities:
  #         - entity: sensor.weathersense_airquality_air_quality_index
  #           name: AQI
  #         - entity: sensor.weathersense_airquality_pm10s
  #           name: PM10S
  #         - entity: sensor.weathersense_airquality_pm10a
  #           name: PM10A
  #     - type: history-graph
  #       # title: Air Quality
  #       hours_to_show: 80
  #       entities:
  #         - entity: sensor.weathersense_airquality_air_quality_index
  #           name: AQI

  - type: vertical-stack
    title: Air Quality (WAQI)
    icon: mdi:factory
    cards:
      - type: entities
        # title: Air Quality (WAQI)
        entities:
          - entity: sensor.waqi_adelaide_cbd
            name: Adelaide CBD
            secondary_info: last-updated
      - type: history-graph
        # title: Air Quality
        hours_to_show: 80
        entities:
          - entity: sensor.waqi_adelaide_cbd
            name: Adelaide

  # - type: vertical-stack
  #   cards:
  #     - type: entities
  #       title: Environment Alerts
  #       entities:
  #         - entity: sensor.gdacs_34_887396_138_630798
  #     - type: map
  #       # title: Environment
  #       geo_location_sources:
  #         - gdacs
  #       entities:
  #         - zone.home
