# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
---
minimum_pre_commit_version: 1.16.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      # - id: check-case-conflict
      # exclude: ^custom_components/
      # - id: check-docstring-first
      - id: check-executables-have-shebangs
        exclude: custom_components/powercalc/
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        args: [--unsafe]
      # - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
        exclude: .HA_VERSION
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: file-contents-sorter
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      # - id: name-tests-test
      # - id: pretty-format-json
      - id: sort-simple-yaml
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  # Format JSON, Markdown and YAML files with Prettier.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        name: Format JSON, Markdown and YAML files
        files: "\\.(\
          json\
          |md|markdown|mdown|mkdn\
          |yaml|yml\
          )$"
        # Do not run on Git push
        stages: [commit]
        verbose: false

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.31.1
    hooks:
      - id: markdownlint

  # - repo: https://github.com/psf/black.git
  #   rev: 21.12b0
  #   hooks:
  #     - id: black

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: "v8.0.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        verbose: false
