---
# lovelace_gen

# Lovelace User Interface
# https://www.home-assistant.io/lovelace/

title: Areas
# background:
views:
  - !include lovelace/areas.yaml
  - !include lovelace/areas/region.yaml
  - !include lovelace/areas/garden.yaml
  - !include lovelace/areas/home.yaml
  - !include lovelace/areas/porch.yaml
  - !include lovelace/areas/fronthall.yaml
  - !include lovelace/areas/living_room.yaml
  - !include lovelace/areas/dining_room.yaml
  - !include lovelace/areas/family_room.yaml
  - !include lovelace/areas/kitchen.yaml
  - !include lovelace/areas/network_cabinet.yaml
  - !include lovelace/areas/utility_room.yaml
  - !include lovelace/areas/bedroom_back.yaml
  - !include lovelace/areas/exercise_room.yaml
  - !include lovelace/areas/bedroom_main.yaml
  - !include lovelace/areas/outside_kitchen.yaml
  - !include lovelace/areas/outside_kitchen.yaml
  - !include lovelace/areas/outside_kitchen/outside_kitchen_battery.yaml
  - !include lovelace/areas/outside_kitchen/outside_kitchen_solar.yaml
