---
# lovelace_gen

# Lovelace User Interface
# https://www.home-assistant.io/lovelace/

title: Irrigation
# background:
views:
  - !include lovelace/irrigation.yaml
  - !include lovelace/irrigation/zones.yaml
  - !include lovelace/irrigation/configuration.yaml

