---
# MQTT
#
# MQTT (aka MQ Telemetry Transport) is a machine-to-machine or
# “Internet of Things” connectivity protocol on top of TCP/IP.
# It allows extremely lightweight publish/subscribe messaging transport.
#
# https://www.home-assistant.io/integrations/mqtt/
#
# get list of clients connected to broker
sensor:
  - platform: rest
    name: MQTT Broker Clients
    resource: http://emqx:18083/api/v4/clients/
    method: GET
    verify_ssl: false
    timeout: 10
    authentication: basic
    username: "admin"
    password: "public"
    scan_interval: 60
    value_template: |
      {% for client in value_json.data %}
        {{ client.clientid }}
      {% endfor %}
    # value_template: "{{ value_json.data[0].clientid }}"
    # json_attributes_path: "$.data[0]"
    # json_attributes:
    #   - clientid
    #   - ip_address
    # value_template: "{{ value_json['items'] }}" #[0].clientid() }}"
