---
# Sensors
#
# https://www.home-assistant.io/integrations/sensor/
#
sensor:
  # Integration - Riemann sum integral
  #
  # https://www.home-assistant.io/integrations/integration/
  #
  - platform: integration
    source: sensor.irrigation_flowrate
    name: Irrigation Water Used
    unique_id: irrigation_water_used
    round: 0
    # unit_prefix: 
    # unit_time: s
    method: trapezoidal

# Utility Meter
#
# https://www.home-assistant.io/integrations/utility_meter/
#
utility_meter:
  irrigation_daily:
    source: sensor.irrigation_water_used
    name: Irrigation use daily
    unique_id: irrigation_use_daily
    cycle: daily
  irrigation_monthly:
    source: sensor.irrigation_water_used
    name: Irrigation use monthly
    unique_id: irrigation_use_monthly
    cycle: monthly
  irrigation_annual:
    source: sensor.irrigation_water_used
    name: Irrigation use annual
    unique_id: irrigation_use_annual
    cycle: yearly

# Timers
#
# https://www.home-assistant.io/integrations/timer/
#
# timer:
#   # Flowmeter updates every 5 minutes when no flow
#   flowmeter_healthcheck_timer:
#     duration: "00:11:00"
#     restore: true
#     restore_grace_period: "00:15:00"

# Automations
#
# https://www.home-assistant.io/docs/automation/basics/
#
# automation:
#   #######################################################################
#   # healthchecks

#   - alias: Flowmeter healthcheck start
#     id: flowmeter_healthcheck_start
#     trigger:
#       - platform: homeassistant
#         event: start
#       - platform: mqtt
#         topic: homeassistant/sensor/deadbeeffeea/flowmeter/state
#     condition: []
#     action:
#       - service: timer.start
#         target:
#           entity_id: timer.flowmeter_healthcheck_timer

#   - alias: Flowmeter healthcheck expired
#     id: flowmeter_healthcheck_expired
#     trigger:
#       - platform: event
#         event_type: timer.finished
#         event_data:
#           entity_id: timer.flowmeter_healthcheck_timer
#     condition: []
#     action:
#       - service: notify.mobile_app_nokia_5_3
#         data:
#           message: Flowmeter silent

#######################################################################
# alerts

# - alias:
