---
# Package: Lights / Standard Lamp

# Automations
#
# https://www.home-assistant.io/docs/automation/basics/
#
automation:
  - id: standard_lamp_on_after_sunset
    alias: Turn standard lamp on after dark
    description: "Turn standard lamp on after sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "+01:00:00"
    condition: []
    action:
      - service: light.turn_on
        target:
          entity_id: light.standard_lamp
        data:
          brightness_pct: 100

  - id: standard_lamp_off_before_sunrise
    alias: Turn standard lamp off before sunrise
    description: "Turn standard lamp off before sunrise"
    mode: single
    trigger:
      - platform: sun
        event: sunrise
        offset: "-01:00:00"
    condition: []
    action:
      - service: light.turn_off
        target:
          entity_id: light.standard_lamp
