---
# Package: People / People

# Template
#
# https://www.home-assistant.io/integrations/template
#
template:
  - binary_sensor:
      - name: "People home"
        state: >-
          {{ is_state('binary_sensor.philip_home', 'on')
            or is_state('binary_sensor.thanh_home', 'on') }}

# Automations
#
# https://www.home-assistant.io/docs/automation/basics/
#
automation:
  - alias: People at home
    id: people_at_home
    description: "People at home"
    trigger:
      - entity_id: sensor.people_home
        platform: state
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            {% if is_state('sensor.people_home', 'on') %}
              'Both home'
            {% else %}
              'No one home'
            {% endif %}
