---
# Package: People / People

# Binary Sensors

binary_sensor:
  # Binary Sensors - Template:

  - platform: template
    sensors:
      people_home:
        value_template: >-
          {{ is_state('binary_sensor.philip_home', 'on')
            or is_state('binary_sensor.thanh_home', 'on') }}

# Input Boolean

input_boolean:

# Automations

automation:
  - alias: People at home
    id: people_at_home
    description: "People at home"
    trigger:
      - entity_id: sensor.people_home
        platform: state
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            {% if is_state('sensor.people_home', 'on') %}
              'Both home'
            {% else %}
              'No one home'
            {% endif %}
