---
# Package: People / Philip

# Person
# Enables Person Component
# https://www.home-assistant.io/integrations/person/
# person:
#   - name: Philip
#     id: philip
#     user_id: !secret person_philip_user_id
#     device_trackers: !secret person_philip_device_tracers

# Binary Sensors

binary_sensor:
  - platform: template

    sensors:
      philip_home:
        value_template: >-
          {{ is_state('device_tracker.philip_mobile', 'home') }}

# Input Boolean

input_boolean:
  # philip_home:
  #   name: Philip at home
  #   icon: mdi:home-account

  philip_bed:
    name: Philip in bed
    icon: mdi:bed

  check_asx_info:
    name: Update ASX prices
    icon: mdi:chart-line

# Sensors

sensor:
  - platform: template
    sensors:
      philip_home_away:
        friendly_name: Philip at home
        value_template: >-
          {% if is_state('binary_sensor.philip_home', 'on') %}
            Home
          {% else %}
            Away
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.philip_home', 'on') %}
            mdi:home-account
          {% else %}
            mdi:home-remove
          {% endif %}

      # Philip's Devices

      # hostname:
      # source_type: router
      philip_phone:
        friendly_name: Philip's Phone
        value_template: >-
          {% if is_state('device_tracker.philip_mobile', 'home') %}
            Online
          {% else %}
            Offline
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.philip_mobile', 'home') %}
            mdi:cellphone
          {% else %}
            mdi:cellphone-nfc-off
          {% endif %}

      # hostname:
      # source_type: router
      # device_tracker.philip_laptop
      philip_laptop:
        friendly_name: Philip's Laptop
        value_template: >-
          {% if is_state('device_tracker.philip_laptop', 'home') %}
            Online
          {% else %}
            Offline
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.philip_laptop', 'home') %}
            mdi:laptop
          {% else %}
            mdi:laptop-off
          {% endif %}

# Automations
automation:
  - alias: Phone battery low
    id: phone_battery_low
    trigger:
      platform: numeric_state
      entity_id: sensor.nokia_5_3_battery_level
      below: 25
    action:
      service: notify.mobile_app_nokia_5_3
      data_template:
        message: >
          "Phone battery level at {{ sensor.nokia_5_3_battery_level }}%. Put on charge."
