---
# Package: Cameras / Perth

# Binary Sensors
# https://www.home-assistant.io/integrations/binary_sensor/

input_boolean:
  camera_perth_recording_status:
    name: "Recording video stream"
    initial: false
    icon: mdi:camera-wireless-outline

  camera_perth_record:
    name: "Record video stream"
    initial: false
    icon: mdi:camera-wireless-outline

# Automations

automation:
  - alias: "Thanh's parents motion"
    id: motion_thanh_parents
    description: Movement at Thanh's parents
    trigger:
      - platform: device
        device_id: !secret nest_camera_living_room_device_id
        domain: nest
        type: camera_motion
    condition:
      - condition: state
        entity_id: input_boolean.camera_perth_record
        state: "on"
      - condition: state
        entity_id: input_boolean.camera_perth_recording_status
        state: "off"
    action:
      - service: camera.snapshot
        target:
          entity_id: camera.living_room
        data:
          filename: '/media/camera/motion_events/living_room-{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg'
      - service: camera.record
        target:
          entity_id: camera.living_room
        data:
          filename: '/media/camera/motion_events/living_room-{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
          duration: 30
      # - service: timer.start
      #   target:
      #     entity_id: timer.camera_record_length
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camera_perth_recording_status
      # - service: notify.mobile_app_nokia_5_3
      #   data:
      #     title: motion detected
      #     message: Thanh parents motion detected
      #     data:
      #       image: /api/camera_proxy/camera.living_room

  # - alias: Camera perth recording status set
  #   id: camera_perth_recording_status_set
  #   trigger:
  #     platform: event
  #     event_type: timer.finished
  #     event_data:
  #       entity_id: timer.camera_record_length
  #   action:
  #     - service: input_boolean.turn_off
  #       target:
  #         entity_id: input_boolean.camera_perth_recording_status
# Timers
# https://www.home-assistant.io/integrations/timer/

# timer:
#   camera_record_length:
#     duration: "00:00:30"
#   camera_record_period:
#     duration: "00:05:00"
