# ---
# Package: Air_and_Space/Air_and_Space

# Customize

# homeassistant:
#   customize:

# binary_sensor.iss:
#   icon: mdi:satellite-variant
#   friendly_name: ISS Visible

# Binary Sensors

# binary_sensor:

# International Space Station (ISS)
# Indicate if the ISS is above your home location
# https://www.home-assistant.io/integrations/iss/
# - platform: iss
# show_on_map: true

# Sensors

sensor:
# OpenSky Network
# Track overhead flights in a given region
# https://www.home-assistant.io/integrations/opensky/
# - platform: opensky
#   radius: !secret opensky_radius_km
#   latitude: !secret home_latitude
#   longitude: !secret home_longitude
#   altitude: !secret opensky_altitude_ceiling_m

# - platform: template
#   sensors:

# iss_peopleinspace:
#   friendly_name: "People in Space"
#   value_template: '{{ states.binary_sensor.iss.attributes["number_of_people_in_space"] }}'

# iss_location:
#   friendly_name: "ISS Location"
#   icon_template: "mdi:satellite-variant"
#   value_template: "{{ states.binary_sensor.iss.state }}"
#   attribute_templates:
#     latitude: '{{ states.binary_sensor.iss.attributes["lat"] }}'
#     longitude: '{{ states.binary_sensor.iss.attributes["long"] }}'

# automation:
#   - alias: Flight entry notification
#     id: flight_entry_notification
#     trigger:
#       platform: event
#       event_type: opensky_entry
#     action:
#       service: notify.mobile_app_nokia_5_3
#       data_template:
#         message: Flight entry of {{ trigger.event.data.callsign }}
