---

# Sensors
#
# https://www.home-assistant.io/integrations/sensor/
#
sensor:
  # https://www.home-assistant.io/integrations/derivative/
  - platform: derivative
    source: sensor.thumper_80ah_voltage
    name: Thumper 80Ah Voltage derivative
    round: 2
    unit_time: min
    # unit: V/m
    # time_window: "00:00:05"

  # https://www.home-assistant.io/integrations/integration/
  - platform: integration
    source: sensor.350w_solar_system_power
    name: 350W Solar System Energy
    # Riemann sum method to be used.
    # Available methods are trapezoidal, left and right
    method: trapezoidal
    round: 2

# Templates
#
# https://www.home-assistant.io/integrations/template/
#
template:
  - sensor:
      - name: 350W Solar System Power
        unique_id: solar_system_350w_power
        device_class: power
        state: >
          {% set power_factor = 1.0 %}
          {% set voltage = 12.0 | float(0.0) %}
          {% set current = (states('sensor.solar_350watt_current') | float(0.0)) / 1000.0 %}
          {% if is_number(voltage) and is_number(current) %}
            {{ (power_factor * current * voltage) | round(1, default=0.0) }}
          {% endif %}
        state_class: measurement
        unit_of_measurement: "W"

  - sensor:
      - name: 350W Solar System Energy Daily Current
        unique_id: solar_system_350w_energy_daily_ah
        device_class: energy
        state: >
          {% set energy = (states('sensor.solar_system_350w_energy_daily') | float(0.0)) %}
          {% if is_number(energy) %}
            {{ (energy / 12.0) | round(1, default=0.0) }}
          {% endif %}
        state_class: measurement
        unit_of_measurement: "Ah"

  # - sensor:
  #     - name: Thumper 80Ah Battery Voltage Gradient
  #       unique_id: thumper_80ah_voltage_gradient
  #       state: >
  #         {% if states.binary_sensor.thumper_80ah_voltage_trend %}
  #           {{ state_attr('binary_sensor.thumper_80ah_voltage_trend', 'gradient') }}
  #         {% endif %}
  #       unit_of_measurement: "V/m"

  # https://community.home-assistant.io/t/binary-sensor-template-format/455585/3
  - binary_sensor:
      - name: Thumper 80Ah battery loaded
        state: >
          {% set battery_derivative = (states('sensor.thumper_80ah_voltage_derivative') | float(0.0)) %}
          {% if is_number(battery_derivative) and battery_derivative < -0.5 %}
            thumper_80ah_battery_loaded == on
          {% endif %}

# Input Boolean
#
# https://www.home-assistant.io/integrations/input_boolean/
#
input_boolean:
  thumper_80ah_battery_boiling_water:
    name: Boiling water
    icon: mdi:kettle-steam

  thumper_80ah_battery_cooking_rice:
    name: Cooking rice
    icon: mdi:rice

  thumper_80ah_battery_heating_milk:
    name: Heating milk
    icon: mdi:coffee

  thumper_80ah_battery_heating_food:
    name: Heating food
    icon: mdi:noodles

# Input Datetime
#
# https://www.home-assistant.io/integrations/input_datetime/
#
input_datetime:
  battery_load_time:
    name: Battery load time
    has_date: false
    has_time: true

# Input Number
#
# https://www.home-assistant.io/integrations/input_number/
#
input_number:
  thumper_80ah_battery_load_time:
    name: Thumper 80Ah Battery Load Time
    initial: 17
    min: 15
    max: 20
    mode: box
    step: 1

  thumper_80ah_battery_voltage_low:
    name: Thumper 80Ah Battery Voltage Low Threshold
    initial: 11.5
    min: 10
    max: 12
    mode: box
    step: 0.1

  thumper_80ah_battery_voltage_high:
    name: Thumper 80Ah Battery Voltage High Threshold
    initial: 12.5
    min: 11
    max: 13
    mode: box
    step: 0.1

# Automations
#
# https://www.home-assistant.io/docs/automation/basics/
#
automation:
  - alias: Thumper 80Ah Voltage Low
    id: thumper_80ah_voltage_low
    trigger:
      # - platform: numeric_state
      #   entity_id: sensor.thumper_80ah_voltage
      #   below: 11.5
      - platform: template
        value_template: "{{ states('sensor.thumper_80ah_voltage') | default(12.0) < states('input_number.thumper_80ah_battery_voltage_low') | default(11.5) }}"
        for:
          minutes: "{{ 3 | default(3) }}"
        id: trigger_thumper_80ah_voltage_low
    condition: []
    action:
      # - variables:
      #     trigger: "{{ trigger.id }}"
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: |
            "Thumper 80Ah battery low voltage at {{ states('sensor.thumper_80ah_voltage') | round(1) }} volts"

  - alias: Thumper 80Ah Voltage High
    id: thumper_80ah_voltage_high
    trigger:
      # - platform: numeric_state
      #   entity_id: sensor.thumper_80ah_voltage
      #   above: 12.5
      - platform: template
        value_template: "{{ states('sensor.thumper_80ah_voltage') | default(12.0) > states('input_number.thumper_80ah_battery_voltage_high') | default(12.5) }}"
        for:
          minutes: "{{ 3 | default(3) }}"
        id: trigger_thumper_80ah_voltage_high
    condition: []
    action:
      # - variables:
      #     trigger: "{{ trigger.id }}"
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: |
            "Thumper 80Ah battery high voltage at {{ states('sensor.thumper_80ah_voltage') | round(1) }} volts"

  - alias: Thumper 80Ah battery load
    id: rice_cooker_timer_start
    trigger:
      - platform: numeric_state
        entity_id: sensor.thumper_80ah_voltage_derivative
        below: -0.5
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Thumper 80Ah battery load"
      # - delay: "00:{{ states('input_number.thumper_80Ah_battery_load_time') | int }}:00"
      # - service: notify.mobile_app_nokia_5_3
      #   data_template:
      #     message: >
      #       "Thumper 80Ah battery needs checking after {{ states('input_number.thumper_80Ah_battery_load_time') | int }} mins"
      - service: timer.start
        data_template:
          entity_id: timer.battery_load
          duration: "{{states('input_datetime.battery_load_time')}}"
        # target:
        # entity_id: timer.battery_load

  - alias: Thumper 80Ah timer expired
    id: thumper_80ah_timer_expired
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.battery_load
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Thumper 80Ah battery needs checking"

# Utility Meter
#
# https://www.home-assistant.io/integrations/utility_meter/
#
utility_meter:
  energy:
    name: 350W Solar Daily Energy
    unique_id: solar_system_350w_energy_daily
    source: sensor.350w_solar_system_energy
    cycle: daily

# Timer
#
# https://www.home-assistant.io/integrations/timer/
#
timer:
  battery_load:
    duration: "00:17:00"

# tv_timer_on:
#   alias: Start TV child protection timer
#   sequence:
#     - service: timer.start
#       data_template:
#         entity_id: timer.tvwatch
#         duration: "{{states('input_datetime.countdowntime')}}"