---
sensor:
  - platform: derivative
    source: sensor.thumper_80ah_voltage
    name: Thumper 80Ah Voltage derivative
    round: 2
    unit_time: min
    # unit: V/m
    # time_window: "00:00:05"

  - platform: integration
    source: sensor.350w_solar_system_power
    name: 350W Solar System Energy
    # Riemann sum method to be used.
    # Available methods are trapezoidal, left and right
    method: trapezoidal
    round: 2

template:
  - sensor:
      - name: 350W Solar System Power
        unique_id: solar_system_350w_power
        device_class: power
        state: >
          {% set power_factor = 1.0 %}
          {% set voltage = 12.0 | float(0.0) %}
          {% set current = (states('sensor.solar_350watt_current') | float(0.0)) / 1000.0 %}
          {% if is_number(voltage) and is_number(current) %}
            {{ (power_factor * current * voltage) | round(1, default=0.0) }}
          {% endif %}
        state_class: measurement
        unit_of_measurement: "W"

  # - sensor:
  #     - name: Thumper 80Ah Battery Voltage Gradient
  #       unique_id: thumper_80ah_voltage_gradient
  #       state: >
  #         {% if states.binary_sensor.thumper_80ah_voltage_trend %}
  #           {{ state_attr('binary_sensor.thumper_80ah_voltage_trend', 'gradient') }}
  #         {% endif %}
  #       unit_of_measurement: "V/m"

  # https://community.home-assistant.io/t/binary-sensor-template-format/455585/3
  - binary_sensor:
      - name: Thumper 80Ah battery loaded
        state: >
          {% set battery_derivative = sensor.thumper_80ah_voltage_derivative %}
          {% if battery_derivative < -0.5 %}
            thumper_80ah_battery_loaded == on
          {% endif %}

automation:
  - alias: Thumper 80Ah Voltage Low
    id: thumper_80ah_voltage_low
    trigger:
      - platform: numeric_state
        entity_id: sensor.thumper_80ah_voltage
        below: 11.5
    condition: []
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Thumper 80Ah battery voltage low"

  - alias: "Thumper 80Ah battery load"
    id: rice_cooker_timer_start
    trigger:
      - platform: numeric_state
        entity_id: sensor.thumper_80ah_voltage_derivative
        below: -0.5
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Thumper 80Ah battery load"
      - delay:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Thumper 80Ah battery needs checking"

utility_meter:
  energy:
    name: 350W Solar Daily Energy
    unique_id: solar_system_350w_energy_daily
    source: sensor.350w_solar_system_energy
    cycle: daily
