---
template:
  - sensor:
      - name: 350W Solar System Power
        unique_id: solar_system_350w_power
        device_class: power
        state: >
          {% set power_factor = 1.0 %}
          {% set voltage = 12.0 | float(0.0) %}
          {% set current = (states('sensor.solar_350watt_current') | float(0.0)) / 1000.0 %}
          {% if is_number(voltage) and is_number(current) %}
          {{ (power_factor * current * voltage) | round(1, default=0.0) }}
          {% endif %}
        state_class: measurement
        unit_of_measurement: "W"

  - binary_sensor:
      - name: Thumper 80Ah Battery Charging
        unique_id: thumper_80ah_voltage_charging
        state: >
          {{ states('sensor.thumper_80ah_voltage_change_per_minute') | float(0.0) > 0.0 }}

      - name: Thumper 80Ah Battery Discharging
        unique_id: thumper_80ah_voltage_discharging
        state: >
          {{ states('sensor.thumper_80ah_voltage_change_per_minute') | float(0.0) < 0.0 }}

binary_sensor:
  # use to trigger a timer when voltage drops by 1 volt / minute
  - platform: trend
    sensors:
      thumper_80ah_voltage_trend:
        entity_id: sensor.thumper_80ah_voltage
        device_class: battery_charging
        friendly_name: Thumper 80Ah Charging
        # invert: false
        # max_samples: 2
        # min_gradient: 0
        # sample_duration: 0

sensor:
  - platform: derivative
    source: sensor.thumper_80ah_voltage
    name: "Thumper 80Ah Voltage change per minute"
    # round: 1
    # unit_time: min
    # time_window: "00:00:05"

  - platform: integration
    source: sensor.350w_solar_system_power
    name: 350W Solar System Energy
    # Riemann sum method to be used.
    # Available methods are trapezoidal, left and right
    method: trapezoidal
    round: 2

timer:
  rice_cooker:
    duration: "00:15:00"

automation:
  - alias: Thumper 80Ah Voltage Low
    id: thumper_80ah_voltage_low
    trigger:
      - platform: numeric_state
        entity_id: sensor.thumper_80ah_voltage
        below: 11.5
    condition: []
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            " Thumper 80Ah battery voltage low"

  - alias: "Rice cooker timer start"
    id: rice_cooker_timer_start
    # Timer is started when the switch pumprun is set to on.
    trigger:
      - platform: state
        entity_id: binary_sensor.thumper_80ah_voltage_falling
        to: "on"
    action:
      - service: timer.start
        target:
          entity_id: timer.rice_cooker
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Rice cooker started"

  # When timer is stopped, the time run out, another message is sent
  - alias: "Rice cooker timer stop"
    id: rice_cooker_timer_stop
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.rice_cooker
    action:
      - service: notify.mobile_app_nokia_5_3
        data_template:
          message: >
            "Rice cooker needs checking"
